name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  apply-codemod:
    name: Apply codemod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codemod repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build codemod
        run: npm run build

      - name: Run tests
        run: npm test
